services:

    app.repository.link:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'AppBundle:Link'

    app.listener.message_receiver:
        class: AppBundle\EventListener\MessageReceivedEventListener
        arguments:
            - "@app.repository.link"
            - "@app.mapper.link"
            - "@app.voter.link"
        tags:
            - { name: kernel.event_listener, event: message.received, method: receiveMessage }

    app.listener.message_sent:
        class: AppBundle\EventListener\MessageSendEventListener
        arguments:
            - "@x_team_slack_messenger.slack.publisher"
            - "%slack.linkbot%"
        tags:
            - { name: kernel.event_listener, event: message.sent, method: sentMessage }

    app.mapper.link:
        class: AppBundle\Mapper\LinkMapper
        arguments:
            - "@x_team_high_five_slack.builder.user"
            - "@x_team_high_five_slack.builder.channel"


    app.voter.link:
        class: AppBundle\Voter\LinkVoter

    app.slack.provider:
         class: AppBundle\Provider\MessageProvider
         arguments:
            - "@x_team_slack_messenger.slack.api.client"
            - "@x_team_slack_messenger.builder.api_object_message_builder"

    app.twig.custom_extension:
         class: AppBundle\Twig\htmlEntityDecodeExtension
         tags:
            - { name: twig.extension }