<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Link;
use Doctrine\ORM\EntityRepository;
use XTeam\HighFiveSlackBundle\Entity\DataManipulator\Period;
use XTeam\HighFiveSlackBundle\Statistic\HighFivesCollection;
use XTeam\SlackMessengerBundle\Model\Message;
use XTeam\HighFiveSlackBundle\Statistic\CollectingStrategy\UserCollectingStrategy;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
    public function getMatch(Message $message)
    {
        $qb = $this->createQueryBuilder('l');

        return $qb
            ->andWhere('l.slackId = :slackId')
            ->setParameter('slackId', $message->getTs() . $message->getChannel()->getId())
            ->orWhere('l.message = :message')
            ->setParameter('message', $message->getText())
            ->getQuery()
            ->getFirstResult();
    }

    public function getLastTimeStamp()
    {
        $link = $this->createQueryBuilder('l')
            ->select('l.createdAt')
            ->setMaxResults(1)
            ->orderBy('l.createdAt', 'DESC')
            ->getQuery()
            ->getArrayResult();

        if (empty($link)) {
            return null;
        }

        return $link[0]['createdAt']->getTimestamp();
    }

    public function getLink(Message $message)
    {
        $highFive  = $this->mapHighFive($message);
        $publisher = $this->userEntityBuilder->getUser($message->getUser());
        $channel   = $this->channelEntityBuilder->getChannel($message->getChannel());

        $highFive->setPublisher($publisher);
        $highFive->setChannel($channel);

        return $highFive;
    }

    public function persist(Link $link)
    {
        return $this->getEntityManager()->persist($link);
    }

    public function findUnsent()
    {
        return $this->findBy(['sent' => 0]);
    }

    public function findUnsentByDate(\DateTime $date = null)
    {
        if (null == $date) {
            $date = new \DateTime();
        }

        $qb = $this->createQueryBuilder('l');

        return $qb
            ->andWhere('l.status = :status')
            ->setParameter('status', Link::STATUS_READY)
            ->andWhere('l.sent = 0')
            ->andWhere($qb->expr()->isNotNull('l.linkInfo'))
            ->andWhere('date(l.createdAt) = :today')
            ->setParameter('today',$date->format('Y-m-d'))
            ->orderBy('l.reactionsCount', 'desc')
            ->groupBy('l.link')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();

    }

    public function findReady()
    {
        $qb = $this->createQueryBuilder('l');

        return $qb
            ->andWhere('l.status = :status')
            ->setParameter('status', Link::STATUS_READY)
            ->andWhere($qb->expr()->isNotNull('l.linkInfo'))
            ->orderBy('l.createdAt', 'desc')
            ->groupBy('l.link')
            ->getQuery()
            ->getResult();
    }
}
